### PR TITLE
Allowed users to use xauth to connect.

### PR DESCRIPTION
**Pull request by charlesduponpon**
This change is backward compatible (or so I believe). I tried it locally with xauth but not with the facebook token. 

From the discussion in https://github.com/charliewolf/pynder/pull/211

### CODE REVIEW

**Comment by cjekel** [comment]
Ah I see that you already did make ```facebook_token=None``` optional.

**Comment by cjekel** [comment]
I don't have write access to your repo, but I believe the only thing this needs is a new default for XAuthToken like in https://github.com/cjekel/tindetheus/commit/ac4896ff6a7fb421603cd0042348c73f749286fd

**Comment by charlesduponpon** [comment]
I believe there is an option on github to allow yourself to have write access on forks of your project. In the meantime, I sent you an invitation to collaborate.

**Comment by cjekel** [comment]
Thanks for creating the XAuth option!

**Pull request merged**
