### PR TITLE
Feature/#32 dotenv

### LINKED ISSUE #32: Use Environment Variables
Using environment variables and `.env` files over a `config.txt` file will make the program more portable and works better with Docker. 

What do you think?

### PR DESCRIPTION
**Pull request by VikashKothary**
Depends on #35. Resolves #32 

If merged, we can then use the environment variables when using the Docker image.

### CODE REVIEW

**Comment by cjekel** [comment]
- [ ] release version 1.0.0 with this change
- [ ] update documentation for this
- [ ] add note in change log
- [ ] test this change on Windows 10 later today

**Comment by cjekel** [comment]
Is there a Windows equivalent to a .env? 

Windows users can either set the environment variables the usual way, or create a local batch script to set them (which they run prior to executing tindetheus). You could do A/B testing with the same model using a.bat and b.bat!

The env.bat file could look like
```bat
@ECHO OFF

rem Tindetheus
set TINDETHEUS_MODEL_DIR=20170512-110547
set TIDETHEUS_IMAGE_BATCH=1000
set TINDETHEUS_DISTANCE=5
set TINDETHEUS_LIKES=100
set TINDETHEUS_RETRIES=20

rem Tinder
set TINDER_AUTH_TOKEN=TODO

rem Facebook
set FACEBOOK_AUTH_TOKEN=TODO
```

This is a great change! and it gets rid of some of the worst code.

**Comment by VikashKothary** [comment]
This is interesting. The above sounds like a suitable solution. It's probably the best for most users because they can set it globally then don't need to worry about it when running the program. 

Another solutions could be to use the https://pypi.org/project/python-dotenv/ library. I planned on using it when creating some example notebooks for #31 and it should work on all OSs. It works by reading the same .env as the Makefile.

**Comment by VikashKothary** [comment]
Please test the new Windows compatibility. Running the project like normal (without the Makefilie) should automatically pick up the `.env` variables. There is also the Windows script like you've suggested.

Regards https://github.com/cjekel/tindetheus/pull/38#issuecomment-600843865, I've updated the documentation. Please have a look and let me know if there's anything I'm missed.

I imagine the version and changelog changes should be make on a separate branch as it is not related to the dotenv feature?

**Comment by cjekel** [comment]
1. So I noticed that the .env would only get picked up (on Windows) from the installation directory (site-packages/tindetheus/.env). I think this has something to do with how I make tindetheus script.
If I moved
```python
from tindetheus import config
```
from the top of tindetheus.py to 
```python
if __name__ == '__main__':
    from tindetheus import config
    command_line_run()
```
the .env would work from a local environment. It's ugly, but works. That shouldn't cause any errors on linux/mac right?  (I can test my linux setup later, but I imagine it should work fine.)

2. Thanks for catching my typos. There's another MIM which could be MITM in getting_started.md

3. There is still a note in the help section of tindetheus.py which needs similar changes to readme.
```python
'''
Settings are stored in your config.txt file. A typically config.txt will
contain the following:
facebook_token = XXXXXXX  # your facebook token hash
model_dir = 20170512-110547  # the location of your model directory
image_batch = 1000  # number of images to load in a batch during train
# the larger the image_batch size, the faster the training process, at the
# cost of additional memory. A 4GB machine may struggle with 1000 images.
distance = 5  # Set the starting distance in miles
likes = 100  # set the number of likes you want to use
# note that free Tinder users only get 100 likes in 24 hours
\n
Optional arguments will overide config.txt settings.
'''
```
could be 
```python
'''
You can now store all default optional parameters in your environment variables! This means you can set your starting distance, number of likes, and image_batch size without manually specifying the options each time. This is an example .env file:
FACEBOOK_AUTH_TOKEN="TODO" # your facebook token hash
# alternatively you can use the XAuthToken
# TINDER_AUTH_TOKEN="TODO"
TINDETHEUS_MODEL_DIR="/models/20170512-110547"  # the location of your facenet model directory
# see https://github.com/davidsandberg/facenet#pre-trained-models for other
# pretrained facenet models
TINDETHEUS_IMAGE_BATCH=1000  # number of images to load in a batch during train
#  the larger the image_batch size, the faster the training process, at the
#  cost of additional memory. A 4GB machine may struggle with 1000 images.
TINDETHEUS_DISTANCE=5  # Set the starting distance in miles
TINDETHEUS_LIKES=100  # set the number of likes you want to use
#  note that free Tinder users only get 100 likes in 24 hours
TINDETHEUS_RETRIES=20
'''
```
4. Version and change log I'll do when I make a new release. No need to worry about these. :) Thanks for the very nice additions. 

5. I'm flagging this as a 1.0.0 release because it breaks some backwards compatibility. Is there anything else you plan on adding to accompany this release?

**Comment by cjekel** [comment]
I should add that the .env works fine on windows when running bits from a jupyter notebook or ipython console, but it doesn't work when calling the runscript tindetheus.exe.

**Comment by cjekel** [comment]
I think the version agnostic way to look for a .env file on windows will end up being
```python
import os
from dotenv import load_dotenv
cwd = os.getcwd()
load_dotenv(dotenv_path=os.path.join(cwd, '.env'))
```

but let me test if that creates linux issues.

**Pull request merged**
